version: '3.3'
services:
    app:
        build: .
        restart: on-failure
        depends_on:
            - db
        ports:
            - '5009:5009'
        environment:
            LOCAL_DATABASE_URL: 'mongodb://db:27017/sae_db'
    db:
        image: 'mongo:3.3'
        restart: on-failure
